name: Auto-publish

on:
  push:
    branches: [main]
    paths:
      - "pyproject.toml"

jobs:
  publish-job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: etils-actions/pypi-auto-publish@v1
